version: "3.5"

networks:
  desafio_network:
    name: desafio_network

services:
  api:
    image: 'webdevops/php-apache-dev:7.4-alpine'
    container_name: desafio-api
    restart: always
    networks:
      desafio_network:
        aliases:
          - desafioapi
    ports:
      - '81:80'
    volumes:
      - ./:/app
    env_file: ./.env

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql-data:/data
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
