version: "3.5"

networks:
  desafio_network:
    name: desafio_network

services:
  api:
    image: 'webdevops/php-apache-dev:7.4-alpine'
    container_name: desafio-api
    restart: always
    networks:
      desafio_network:
        aliases:
          - desafioapi
    ports:
      - '8181:80'
    volumes:
      - ./:/app
    env_file: ./.env

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "desafio"
    ports:
      - 3306:3306
    networks:
      desafio_network:
        aliases:
          - mysqldb

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      desafio_network:
        aliases:
          - adminer
